HW5
================
Lauren Richter
2021-11-20

## Problem 1

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## `summarise()` has grouped output by 'city_state', 'disposition'. You can override using the `.groups` argument.
    ## # A tibble: 6 × 3
    ## # Groups:   city_state [6]
    ##   city_state      n_unsolved total_homicides
    ##   <fct>                <int>           <int>
    ## 1 Albuquerque, NM        146             378
    ## 2 Atlanta, GA            373             973
    ## 3 Baltimore, MD         1825            2827
    ## 4 Baton Rouge, LA        196             424
    ## 5 Birmingham, AL         347             800
    ## 6 Boston, MA             310             614

The raw data includes 52179 observations of 12 variables for homicides
in the 50 largest US cities (by population in 2012). Each record
includes information about the victim, the date of the report, the
location of the homicide, and the disposition of the case (whether an
arrest was made). The named variables are uid, reported_date,
victim_last, victim_first, victim_race, victim_age, victim_sex, city,
state, lat, lon, disposition. More information about the data is
available from the original data source,
[here](https://github.com/washingtonpost/data-homicides).

    ## # A tibble: 1 × 6
    ##   city_state    n_unsolved total_homicides estimate conf_low conf_high
    ##   <chr>              <int>           <int>    <dbl>    <dbl>     <dbl>
    ## 1 Baltimore, MD       1825            2827    0.646    0.628     0.663

For the city of Baltimore, MD, the estimated proportion is 0.646 (95%
confidence interval \[0.628, 0.663\])

Now run prop.test for each of the cities in your dataset, and extract
both the proportion of unsolved homicides and the confidence interval
for each. Do this within a “tidy” pipeline, making use of purrr::map,
purrr::map2, list columns and unnest as necessary to create a tidy
dataframe with estimated proportions and CIs for each city.

``` r
homicide_df = homicide_df %>% 
  group_by(city_state) %>% 
  mutate(
    test_results = map2(n_unsolved, total_homicides, prop.test),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, n_unsolved, total_homicides, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, n_unsolved, total_homicides, estimate, conf.low, conf.high) %>%
  janitor::clean_names("snake")
## Warning in .f(.x[[1L]], .y[[1L]], ...): Chi-squared approximation may be
## incorrect

homicide_df
## # A tibble: 51 × 6
## # Groups:   city_state [51]
##    city_state      n_unsolved total_homicides estimate conf_low conf_high
##    <fct>                <int>           <int>    <dbl>    <dbl>     <dbl>
##  1 Albuquerque, NM        146             378    0.386    0.337     0.438
##  2 Atlanta, GA            373             973    0.383    0.353     0.415
##  3 Baltimore, MD         1825            2827    0.646    0.628     0.663
##  4 Baton Rouge, LA        196             424    0.462    0.414     0.511
##  5 Birmingham, AL         347             800    0.434    0.399     0.469
##  6 Boston, MA             310             614    0.505    0.465     0.545
##  7 Buffalo, NY            319             521    0.612    0.569     0.654
##  8 Charlotte, NC          206             687    0.300    0.266     0.336
##  9 Chicago, IL           4073            5535    0.736    0.724     0.747
## 10 Cincinnati, OH         309             694    0.445    0.408     0.483
## # … with 41 more rows
```

Cities shown with estimated proportion of unsolved homicides (95%
confidence interval).

``` r
homicide_df %>% 
  ungroup() %>%
  mutate(city_state = fct_reorder(city_state, desc(estimate))) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

![](p8105_hw5_lr2854_files/figure-gfm/city_estimates-1.png)<!-- -->
